spring:
  application:
    name: Enotes_API_Service
  profiles:
    active: prod
    
--- 
#Dev Config
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vohra@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com 
    username: 
    password: 
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true 

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: "/enotes-doc"
  api-docs:
    path: "/enotes-api-doc"  
server:
  port: 8080
file:
  upload:
    path: notes/


---
#Test Config
spring:
  config:
    activate:
      on-profile: test
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/enotes_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vohra@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com 
    username: 
    password: 
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true 
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: "/enotes-doc"
  api-docs:
    path: "/enotes-api-doc"  
server:
  port: 8081
          
file:
  upload:
    path: notes/

    
---
#Uat Config
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/enotes_uat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vohra@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com 
    username: 
    password: 
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true 
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: "/enotes-doc"
  api-docs:
    path: "/enotes-api-doc"  
          
file:
  upload:
    path: notes/    
    
    
---
#prod Config
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/enotes_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vohra@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com 
    username: 
    password: 
    port: 587
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true 
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: "/enotes-doc"
  api-docs:
    path: "/enotes-api-doc"  
server:
  port: 8082
          
file:
  upload:
    path: notes/    
    